#!/bin/bash

SRC_DIR="../src"
CHROME_BUILD_CMD="./build"
CHROME_BUILD_FLAGS=""
WEBVIEW_SWITCH_CMD="./webview-switch"
WEBVIEW_SWITCH_FLAGS=""
MOBILE_MANIFEST="../src/manifest.mobile.json"
CONFIG_XML="./config.xml"
CCA_FLAGS="--debug"

while getopts "rk" OPT; do
   case $OPT in
      r)
         CHROME_BUILD_FLAGS="-r"
         CCA_FLAGS="--release"
         ;;
      k)
	# KitKat-specific. (API 19, system webview)
	WEBVIEW_SWITCH_FLAGS="-s"
	;;
   esac
done

set -e

pushd $SRC_DIR
"$CHROME_BUILD_CMD" $CHROME_BUILD_FLAGS
popd
"$WEBVIEW_SWITCH_CMD" $WEBVIEW_SWITCH_FLAGS -m "$MOBILE_MANIFEST" -c "$CONFIG_XML"
cca build $CCA_FLAGS

exit 0

# New CCA seems to zipalign automatically now.
if [ "$CCA_FLAGS" == "--release" ]; then
   echo "Running zipalign"
   RELEASE_APKS="platforms/android/build/outputs/apk/android*-release.apk"
   for INFILE in $RELEASE_APKS; do
      OUTFILE=`echo "$INFILE" | sed -e 's~^\(.\+\).apk$~\1-aligned.apk~g'`
      zipalign -f 4 "$INFILE" "$OUTFILE"
      echo "Aligned $OUTFILE"
   done
fi

exit 0
