#!/bin/bash

BUILD_CMD="./build"
BUILD_FLAGS=""
CCA_FLAGS="--debug"
CCA_TARGET=""

while getopts "rkdet:" OPT; do
   case $OPT in
      r)
         BUILD_FLAGS="$BUILD_FLAGS -r"
         CCA_FLAGS="--release"
         ;;
      d)
         CCA_TARGET="--device"
         ;;
      e)
         CCA_TARGET="--emulator"
         ;;
      t)
         CCA_TARGET="--target=$OPTARG"
         ;;
		k)
			BUILD_FLAGS="$BUILD_FLAGS -k"
			;;
   esac
done

set -e
$BUILD_CMD $BUILD_FLAGS
echo "Deploying..."
cca run --nobuild $CCA_FLAGS $CCA_TARGET

exit 0
