#!/bin/bash

SRC_DIR="./src"
CHROME_BUILD_CMD="./build"
CHROME_BUILD_FLAGS="-r"
OUTPUT_FILE="./app.zip"

while getopts "o:" OPT; do
   case $OPT in
      o)
         OUTPUT_FILE="../$OPTARG"
         ;;
   esac
done

set -e

pushd $SRC_DIR

$CHROME_BUILD_CMD $CHROME_BUILD_FLAGS

if [ -f "$OUTPUT_FILE" ]; then
   rm "$OUTPUT_FILE"
fi
zip "$OUTPUT_FILE" *.compiled.js *.css *.html *.png manifest.json background.js img/*

popd
